### ISSUE TITLE
A typo in the example script?

### ISSUE THREAD

**Issue by poralix** [cvmiller/expand6#1]
Hello,

https://github.com/cvmiller/expand6/blob/ac2f03c5bf594896212ae1a00aa24abb2947bdf8/expand6_example.sh#L21

Shouldn't it be **addr1=2001:db8:123::5** instead of **addr1=2001:db8:123::56**

Regards,
Alex.

**Comment by cvmiller** [comment]
Good catch! Yes, I was testing that the negative would also be detected, but failed to remove the '6' before committing the code. Fixed in v.94.

thanks
